# Generated by Django 5.0.2 on 2024-02-19 00:14

import django.core.validators

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_iof_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
